[package]
name = "baram-openfoam"
version = "0.1.0"
edition = "2024"

[dependencies]
baram-core = { path = "../baram-core" }
baram-mesh = { path = "../baram-mesh" }
serde      = { workspace = true }
serde_json = { workspace = true }
anyhow     = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
tokio      = { workspace = true }
