[package]
name = "baram-mesh"
version = "0.1.0"
edition = "2024"

[dependencies]
baram-core = { path = "../baram-core" }
serde      = { workspace = true }
serde_json = { workspace = true }
anyhow     = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
nalgebra   = { workspace = true }
bytemuck   = { workspace = true }
rayon      = { workspace = true }
nom        = { workspace = true }
truck-stepio = "0.3"
truck-meshalgo = "0.4"
