[package]
name = "baram-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
baram-core = { path = "../baram-core" }
baram-mesh = { path = "../baram-mesh" }
wgpu       = { workspace = true }
glam       = { workspace = true }
bytemuck   = { workspace = true }
tracing    = { workspace = true }
winit      = { workspace = true }
pollster   = { workspace = true }
tracing-subscriber = { workspace = true }
